
    alter table TC_CATEGORY 
        drop constraint FK15120CEE211608D;

    alter table TC_CITY 
        drop constraint FKD33A6D3B1C309431;

    alter table TC_CUSTOMER 
        drop constraint FK226FE3AE8D3D09E7;

    alter table TC_DEPARTMENT 
        drop constraint FKD6D2EF228D3D09E7;

    alter table TC_ENTERPRISE 
        drop constraint FK746BDF318D3D09E7;

    alter table TC_INVOICE 
        drop constraint FK2233A13D5C051C9B;

    alter table TC_ORDERS 
        drop constraint FK3457EB58D3D09E7;

    alter table TC_ORDERS 
        drop constraint FK3457EB5244EE64D;

    alter table TC_ORDER_ITEM 
        drop constraint FKD318A9545C051C9B;

    alter table TC_ORDER_ITEM 
        drop constraint FKD318A9548FA01D2D;

    alter table TC_PRICE_LIST_ITEM 
        drop constraint FKEDB0ECAEA80F8A7D;

    alter table TC_PRICE_LIST_ITEM 
        drop constraint FKEDB0ECAE8FA01D2D;

    alter table TC_PRODUCT 
        drop constraint FK9AEB2AFFE211608D;

    alter table TC_VENDOR 
        drop constraint FKE84C1188D3D09E7;

    drop table TC_CATEGORY if exists;

    drop table TC_CITY if exists;

    drop table TC_CUSTOMER if exists;

    drop table TC_DEPARTMENT if exists;

    drop table TC_ENTERPRISE if exists;

    drop table TC_INVOICE if exists;

    drop table TC_ORDERS if exists;

    drop table TC_ORDER_ITEM if exists;

    drop table TC_PAYMENT if exists;

    drop table TC_PRICE_LIST if exists;

    drop table TC_PRICE_LIST_ITEM if exists;

    drop table TC_PRODUCT if exists;

    drop table TC_STATE if exists;

    drop table TC_USER if exists;

    drop table TC_VENDOR if exists;

    create table TC_CATEGORY (
        ID bigint generated by default as identity unique,
        CAT_DESCRIPTION varchar(255) not null,
        CAT_NAME varchar(255) not null,
        category bigint,
        primary key (ID)
    );

    create table TC_CITY (
        ID bigint generated by default as identity unique,
        CIT_NAME varchar(255) not null,
        CIT_ZIP_CODE varchar(255) not null,
        state bigint,
        primary key (ID)
    );

    create table TC_CUSTOMER (
        ID bigint generated by default as identity unique,
        CUS_ADDRESS varchar(255) not null,
        CUS_FIRST_NAME varchar(255) not null,
        CUS_LAST_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    create table TC_DEPARTMENT (
        ID bigint generated by default as identity unique,
        DEP_DEPARTMENT_ADDRESS varchar(255) not null,
        DEP_DEPARTMENT_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    create table TC_ENTERPRISE (
        ID bigint generated by default as identity unique,
        ENT_ADDRESS varchar(255) not null,
        ENT_ENTERPRISE_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    create table TC_INVOICE (
        ID bigint generated by default as identity unique,
        INV_INVOICE_DATE timestamp not null,
        INV_INVOICE_NUMBER varchar(255) not null,
        INV_TOTAL decimal(19,2) not null,
        orders bigint,
        primary key (ID)
    );

    create table TC_ORDERS (
        ID bigint generated by default as identity unique,
        ORD_ORDER_DATE timestamp not null,
        ORD_ORDER_NUMBER varchar(255) not null,
        ORD_ORDER_STATUS varchar(255) not null,
        ORD_ORDER_TOTAL decimal(19,2) not null,
        ORD_SHIPMENT_ADDRESS varchar(255) not null,
        city bigint,
        customer bigint,
        primary key (ID)
    );

    create table TC_ORDER_ITEM (
        ID bigint generated by default as identity unique,
        OI_AVAILABLE boolean not null,
        OI_ORDERED_QUANTITY varchar(255) not null,
        OI_UNIT_PRICE decimal(19,2) not null,
        OI_UNIT_TAX decimal(19,2) not null,
        OI_VALUE decimal(19,2) not null,
        orders bigint,
        product bigint,
        primary key (ID)
    );

    create table TC_PAYMENT (
        ID bigint generated by default as identity unique,
        PAY_AMOUNT_RECIEVED decimal(19,2) not null,
        PAY_DATE_RECIEVED timestamp not null,
        PAY_PAYMENT_METHOD varchar(255) not null,
        primary key (ID)
    );

    create table TC_PRICE_LIST (
        ID bigint generated by default as identity unique,
        PL_ACTIVE_FROM_DATE timestamp not null,
        PL_PRICE_LIST_NUMBER varchar(255) not null,
        primary key (ID)
    );

    create table TC_PRICE_LIST_ITEM (
        ID bigint generated by default as identity unique,
        PLI_PRICE decimal(19,2) not null,
        PLI_TAX decimal(19,2) not null,
        priceList bigint,
        product bigint,
        primary key (ID)
    );

    create table TC_PRODUCT (
        ID bigint generated by default as identity unique,
        PRO_DESCRIPTION varchar(255) not null,
        PRO_NAME varchar(255) not null,
        category bigint,
        primary key (ID)
    );

    create table TC_STATE (
        ID bigint generated by default as identity unique,
        STA_NAME varchar(255) not null,
        primary key (ID)
    );

    create table TC_USER (
        ID bigint generated by default as identity unique,
        password varchar(255) not null unique,
        username varchar(255) not null unique,
        primary key (ID)
    );

    create table TC_VENDOR (
        ID bigint generated by default as identity unique,
        VEN_ADDRESS varchar(255) not null,
        VEN_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    alter table TC_CATEGORY 
        add constraint FK15120CEE211608D 
        foreign key (category) 
        references TC_CATEGORY;

    alter table TC_CITY 
        add constraint FKD33A6D3B1C309431 
        foreign key (state) 
        references TC_STATE;

    alter table TC_CUSTOMER 
        add constraint FK226FE3AE8D3D09E7 
        foreign key (city) 
        references TC_CITY;

    alter table TC_DEPARTMENT 
        add constraint FKD6D2EF228D3D09E7 
        foreign key (city) 
        references TC_CITY;

    alter table TC_ENTERPRISE 
        add constraint FK746BDF318D3D09E7 
        foreign key (city) 
        references TC_CITY;

    alter table TC_INVOICE 
        add constraint FK2233A13D5C051C9B 
        foreign key (orders) 
        references TC_ORDERS;

    alter table TC_ORDERS 
        add constraint FK3457EB58D3D09E7 
        foreign key (city) 
        references TC_CITY;

    alter table TC_ORDERS 
        add constraint FK3457EB5244EE64D 
        foreign key (customer) 
        references TC_CUSTOMER;

    alter table TC_ORDER_ITEM 
        add constraint FKD318A9545C051C9B 
        foreign key (orders) 
        references TC_ORDERS;

    alter table TC_ORDER_ITEM 
        add constraint FKD318A9548FA01D2D 
        foreign key (product) 
        references TC_PRODUCT;

    alter table TC_PRICE_LIST_ITEM 
        add constraint FKEDB0ECAEA80F8A7D 
        foreign key (priceList) 
        references TC_PRICE_LIST;

    alter table TC_PRICE_LIST_ITEM 
        add constraint FKEDB0ECAE8FA01D2D 
        foreign key (product) 
        references TC_PRODUCT;

    alter table TC_PRODUCT 
        add constraint FK9AEB2AFFE211608D 
        foreign key (category) 
        references TC_CATEGORY;

    alter table TC_VENDOR 
        add constraint FKE84C1188D3D09E7 
        foreign key (city) 
        references TC_CITY;
