
    alter table PRO_MANUFACTURER 
        drop constraint FK90AB0C438D3D09E7;

    alter table PRO_OWNER 
        drop constraint FK952DB6618D3D09E7;

    alter table PRO_OWNER 
        drop constraint FK952DB66199338277;

    drop table PRO_CAR if exists;

    drop table PRO_CITY if exists;

    drop table PRO_MANUFACTURER if exists;

    drop table PRO_OWNER if exists;

    drop table PRO_USER if exists;

    create table PRO_CAR (
        ID bigint generated by default as identity unique,
        CAR_MODEL varchar(255) not null,
        primary key (ID)
    );

    create table PRO_CITY (
        ID bigint generated by default as identity unique,
        CIT_DESCRIPTION varchar(255) not null,
        CIT_NAME varchar(255) not null,
        primary key (ID)
    );

    create table PRO_MANUFACTURER (
        ID bigint generated by default as identity unique,
        MAN_NAME varchar(255) not null,
        MAN_TYPE varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    create table PRO_OWNER (
        ID bigint generated by default as identity unique,
        OWN_ADDRESS varchar(255) not null,
        OWN_IMAL_ZENU boolean not null,
        OWN_NAME varchar(255) not null,
        OWN_OPIS varchar(255) not null,
        car bigint,
        city bigint,
        primary key (ID)
    );

    create table PRO_USER (
        ID bigint generated by default as identity unique,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (ID)
    );

    alter table PRO_MANUFACTURER 
        add constraint FK90AB0C438D3D09E7 
        foreign key (city) 
        references PRO_CITY;

    alter table PRO_OWNER 
        add constraint FK952DB6618D3D09E7 
        foreign key (city) 
        references PRO_CITY;

    alter table PRO_OWNER 
        add constraint FK952DB66199338277 
        foreign key (car) 
        references PRO_CAR;
