
    alter table CITY 
        drop constraint FK1F916B1C309431;

    alter table CUSTOMER 
        drop constraint FK52C76FDE8D3D09E7;

    alter table DEPARTMENT 
        drop constraint FK4F782F528D3D09E7;

    alter table ENTERPRISE 
        drop constraint FKED111F618D3D09E7;

    alter table INVOICE 
        drop constraint FK9FA1CF0D5C051C9B;

    alter table ORDERITEM 
        drop constraint FK8ECABB415C051C9B;

    alter table ORDERITEM 
        drop constraint FK8ECABB418FA01D2D;

    alter table ORDERS 
        drop constraint FK8B7256E58D3D09E7;

    alter table ORDERS 
        drop constraint FK8B7256E5244EE64D;

    alter table PRICELISTITEM 
        drop constraint FKD99F1CDAA80F8A7D;

    alter table PRICELISTITEM 
        drop constraint FKD99F1CDA8FA01D2D;

    alter table PRODUCT 
        drop constraint FK185958CFE211608D;

    alter table VENDOR 
        drop constraint FK96B199488D3D09E7;

    drop table CATEGORY if exists;

    drop table CITY if exists;

    drop table CUSTOMER if exists;

    drop table DEPARTMENT if exists;

    drop table ENTERPRISE if exists;

    drop table INVOICE if exists;

    drop table ORDERITEM if exists;

    drop table ORDERS if exists;

    drop table PAYMENT if exists;

    drop table PRICELIST if exists;

    drop table PRICELISTITEM if exists;

    drop table PRODUCT if exists;

    drop table STATE if exists;

    drop table USER if exists;

    drop table VENDOR if exists;

    create table CATEGORY (
        ID bigint generated by default as identity unique,
        CAT_DESCRIPTION varchar(255) not null,
        CAT_NAME varchar(255) not null,
        primary key (ID)
    );

    create table CITY (
        ID bigint generated by default as identity unique,
        CIT_NAME varchar(255) not null,
        CIT_ZIP_CODE varchar(255) not null,
        state bigint,
        primary key (ID)
    );

    create table CUSTOMER (
        ID bigint generated by default as identity unique,
        CUS_ADDRESS varchar(255) not null,
        CUS_FIRST_NAME varchar(255) not null,
        CUS_LAST_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    create table DEPARTMENT (
        ID bigint generated by default as identity unique,
        DEP_DEPARTMENT_ADDRESS varchar(255) not null,
        DEP_DEPARTMENT_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    create table ENTERPRISE (
        ID bigint generated by default as identity unique,
        ENT_ADDRESS varchar(255) not null,
        ENT_ENTERPRISE_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    create table INVOICE (
        ID bigint generated by default as identity unique,
        INV_INVOICE_DATE timestamp not null,
        INV_INVOICE_NUMBER varchar(255) not null,
        INV_TOTAL decimal(19,2) not null,
        orders bigint,
        primary key (ID)
    );

    create table ORDERITEM (
        ID bigint generated by default as identity unique,
        OI_AVAILABLE boolean not null,
        OI_ORDERED_QUANTITY varchar(255) not null,
        OI_UNIT_PRICE decimal(19,2) not null,
        OI_UNIT_TAX decimal(19,2) not null,
        OI_VALUE decimal(19,2) not null,
        orders bigint,
        product bigint,
        primary key (ID)
    );

    create table ORDERS (
        ID bigint generated by default as identity unique,
        ORD_ORDER_DATE timestamp not null,
        ORD_ORDER_NUMBER varchar(255) not null,
        ORD_ORDER_STATUS varchar(255) not null,
        ORD_ORDER_TOTAL decimal(19,2) not null,
        ORD_SHIPMENT_ADDRESS varchar(255) not null,
        city bigint,
        customer bigint,
        primary key (ID)
    );

    create table PAYMENT (
        ID bigint generated by default as identity unique,
        PAY_AMOUNT_RECIEVED decimal(19,2) not null,
        PAY_DATE_RECIEVED timestamp not null,
        PAY_PAYMENT_METHOD varchar(255) not null,
        primary key (ID)
    );

    create table PRICELIST (
        ID bigint generated by default as identity unique,
        PL_ACTIVE_FROM_DATE timestamp not null,
        PL_PRICE_LIST_NUMBER varchar(255) not null,
        primary key (ID)
    );

    create table PRICELISTITEM (
        ID bigint generated by default as identity unique,
        PLI_PRICE decimal(19,2) not null,
        PLI_TAX decimal(19,2) not null,
        priceList bigint,
        product bigint,
        primary key (ID)
    );

    create table PRODUCT (
        ID bigint generated by default as identity unique,
        PRO_DESCRIPTION varchar(255) not null,
        PRO_NAME varchar(255) not null,
        category bigint,
        primary key (ID)
    );

    create table STATE (
        ID bigint generated by default as identity unique,
        STA_NAME varchar(255) not null,
        primary key (ID)
    );

    create table USER (
        ID bigint generated by default as identity unique,
        password varchar(255) not null unique,
        username varchar(255) not null unique,
        primary key (ID)
    );

    create table VENDOR (
        ID bigint generated by default as identity unique,
        VEN_ADDRESS varchar(255) not null,
        VEN_NAME varchar(255) not null,
        city bigint,
        primary key (ID)
    );

    alter table CITY 
        add constraint FK1F916B1C309431 
        foreign key (state) 
        references STATE;

    alter table CUSTOMER 
        add constraint FK52C76FDE8D3D09E7 
        foreign key (city) 
        references CITY;

    alter table DEPARTMENT 
        add constraint FK4F782F528D3D09E7 
        foreign key (city) 
        references CITY;

    alter table ENTERPRISE 
        add constraint FKED111F618D3D09E7 
        foreign key (city) 
        references CITY;

    alter table INVOICE 
        add constraint FK9FA1CF0D5C051C9B 
        foreign key (orders) 
        references ORDERS;

    alter table ORDERITEM 
        add constraint FK8ECABB415C051C9B 
        foreign key (orders) 
        references ORDERS;

    alter table ORDERITEM 
        add constraint FK8ECABB418FA01D2D 
        foreign key (product) 
        references PRODUCT;

    alter table ORDERS 
        add constraint FK8B7256E58D3D09E7 
        foreign key (city) 
        references CITY;

    alter table ORDERS 
        add constraint FK8B7256E5244EE64D 
        foreign key (customer) 
        references CUSTOMER;

    alter table PRICELISTITEM 
        add constraint FKD99F1CDAA80F8A7D 
        foreign key (priceList) 
        references PRICELIST;

    alter table PRICELISTITEM 
        add constraint FKD99F1CDA8FA01D2D 
        foreign key (product) 
        references PRODUCT;

    alter table PRODUCT 
        add constraint FK185958CFE211608D 
        foreign key (category) 
        references CATEGORY;

    alter table VENDOR 
        add constraint FK96B199488D3D09E7 
        foreign key (city) 
        references CITY;
