
    alter table Adapt_Permission 
        drop constraint FK636FFB4C1AEA0D6D;

    alter table Adapt_Permission 
        drop constraint FK636FFB4CF4F3CF9D;

    alter table Adapt_ResourceHierarchy 
        drop constraint FK1E8CB1AA1AEA0D6D;

    alter table Adapt_ResourceHierarchy 
        drop constraint FK1E8CB1AAB90B0743;

    alter table Adapt_RolePermission 
        drop constraint FK93C0B5E2386ED6BD;

    alter table Adapt_RolePermission 
        drop constraint FK93C0B5E26B5200AF;

    alter table Adapt_UserRoles 
        drop constraint FK728E0095386ED6BD;

    alter table Adapt_UserRoles 
        drop constraint FK728E00953871AD67;

    drop table ADAPT_ACTION if exists;

    drop table Adapt_Operation if exists;

    drop table Adapt_Permission if exists;

    drop table Adapt_Resource if exists;

    drop table Adapt_ResourceHierarchy if exists;

    drop table Adapt_Role if exists;

    drop table Adapt_RolePermission if exists;

    drop table Adapt_User if exists;

    drop table Adapt_UserRoles if exists;

    create table ADAPT_ACTION (
        ID bigint generated by default as identity unique,
        ACT_BTN_ID varchar(255) not null,
        ACT_IMG_PATH varchar(255) not null,
        ACT_LINK varchar(255) not null,
        ACT_NAME varchar(255) not null,
        ACT_TIP varchar(255) not null,
        ACT_TYPE varchar(255) not null,
        primary key (ID)
    );

    create table Adapt_Operation (
        id integer generated by default as identity unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table Adapt_Permission (
        id integer generated by default as identity unique,
        name varchar(255) not null,
        operation integer,
        resource integer not null,
        primary key (id)
    );

    create table Adapt_Resource (
        id integer generated by default as identity unique,
        link varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table Adapt_ResourceHierarchy (
        id integer generated by default as identity unique,
        resource integer not null,
        resource2 integer not null,
        primary key (id)
    );

    create table Adapt_Role (
        id integer generated by default as identity unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table Adapt_RolePermission (
        id integer generated by default as identity unique,
        permission integer not null,
        role integer not null,
        primary key (id)
    );

    create table Adapt_User (
        id integer generated by default as identity unique,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );

    create table Adapt_UserRoles (
        id integer generated by default as identity unique,
        valid boolean,
        role integer not null,
        user integer not null,
        primary key (id)
    );

    alter table Adapt_Permission 
        add constraint FK636FFB4C1AEA0D6D 
        foreign key (resource) 
        references Adapt_Resource;

    alter table Adapt_Permission 
        add constraint FK636FFB4CF4F3CF9D 
        foreign key (operation) 
        references Adapt_Operation;

    alter table Adapt_ResourceHierarchy 
        add constraint FK1E8CB1AA1AEA0D6D 
        foreign key (resource) 
        references Adapt_Resource;

    alter table Adapt_ResourceHierarchy 
        add constraint FK1E8CB1AAB90B0743 
        foreign key (resource2) 
        references Adapt_Resource;

    alter table Adapt_RolePermission 
        add constraint FK93C0B5E2386ED6BD 
        foreign key (role) 
        references Adapt_Role;

    alter table Adapt_RolePermission 
        add constraint FK93C0B5E26B5200AF 
        foreign key (permission) 
        references Adapt_Permission;

    alter table Adapt_UserRoles 
        add constraint FK728E0095386ED6BD 
        foreign key (role) 
        references Adapt_Role;

    alter table Adapt_UserRoles 
        add constraint FK728E00953871AD67 
        foreign key (user) 
        references Adapt_User;
