
    alter table Permission 
        drop constraint FK57F7A1EFB3636EAD;

    alter table Permission 
        drop constraint FK57F7A1EF6BA6965D;

    alter table ResourceHierarchy 
        drop constraint FK7B9DDDA751846883;

    alter table ResourceHierarchy 
        drop constraint FK7B9DDDA7B3636EAD;

    alter table RolePermission 
        drop constraint FK18FE53058D4AD7FD;

    alter table RolePermission 
        drop constraint FK18FE5305CAF811EF;

    alter table UserRoles 
        drop constraint FK8AF579928D4AD7FD;

    alter table UserRoles 
        drop constraint FK8AF579928D4DAEA7;

    drop table ADAPT_ACTION if exists;

    drop table Operation if exists;

    drop table Permission if exists;

    drop table Resource if exists;

    drop table ResourceHierarchy if exists;

    drop table Role if exists;

    drop table RolePermission if exists;

    drop table User if exists;

    drop table UserRoles if exists;

    create table ADAPT_ACTION (
        ID bigint generated by default as identity unique,
        ACT_BTN_ID varchar(255) not null,
        ACT_IMG_PATH varchar(255) not null,
        ACT_LINK varchar(255) not null,
        ACT_NAME varchar(255) not null,
        ACT_TIP varchar(255) not null,
        ACT_TYPE varchar(255) not null,
        primary key (ID)
    );

    create table Operation (
        id integer generated by default as identity unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table Permission (
        id integer generated by default as identity unique,
        name varchar(255) not null,
        operation integer,
        resource integer not null,
        primary key (id)
    );

    create table Resource (
        id integer generated by default as identity unique,
        link varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table ResourceHierarchy (
        id integer generated by default as identity unique,
        resource integer not null,
        resource2 integer not null,
        primary key (id)
    );

    create table Role (
        id integer generated by default as identity unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table RolePermission (
        id integer generated by default as identity unique,
        permission integer not null,
        role integer not null,
        primary key (id)
    );

    create table User (
        id integer generated by default as identity unique,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );

    create table UserRoles (
        id integer generated by default as identity unique,
        valid boolean,
        role integer not null,
        user integer not null,
        primary key (id)
    );

    alter table Permission 
        add constraint FK57F7A1EFB3636EAD 
        foreign key (resource) 
        references Resource;

    alter table Permission 
        add constraint FK57F7A1EF6BA6965D 
        foreign key (operation) 
        references Operation;

    alter table ResourceHierarchy 
        add constraint FK7B9DDDA751846883 
        foreign key (resource2) 
        references Resource;

    alter table ResourceHierarchy 
        add constraint FK7B9DDDA7B3636EAD 
        foreign key (resource) 
        references Resource;

    alter table RolePermission 
        add constraint FK18FE53058D4AD7FD 
        foreign key (role) 
        references Role;

    alter table RolePermission 
        add constraint FK18FE5305CAF811EF 
        foreign key (permission) 
        references Permission;

    alter table UserRoles 
        add constraint FK8AF579928D4AD7FD 
        foreign key (role) 
        references Role;

    alter table UserRoles 
        add constraint FK8AF579928D4DAEA7 
        foreign key (user) 
        references User;
